name: app_001
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_isolate: ^2.1.0
  shared_preferences: ^2.0.13
  flutter_map: ^7.0.2
  flutter_map_geojson: ^1.0.8
  gradient_icon: ^2.0.9
  http: ^1.2.2
  intl: ^0.20.1
  latlong2: ^0.9.1
  permission_handler: ^12.0.0+1
  rainbow_color: ^2.0.1
  transparent_image: ^2.0.1
  weather_icons: ^3.0.0
  webview_flutter: ^4.10.0
  info_popup: ^4.3.2
  toggle_switch: ^2.3.0
  choice: ^2.3.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/
